version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=poojankhatri
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always
  customerservice:                        #it is just a name, which will be used only in this file.
    image: customer-service               #name of the image after dockerfile executes
    container_name: customer-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8084:8084"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/outreach_portal?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: poojankhatri